version: '3.8'

services:
  app: 
    build:  
      context: ./php
    image: app
    container_name: app
    volumes:
      - ./www:/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: giant
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: test_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化 SQL 文件

volumes:
  mysql_data:
